--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Theslowaja/BossBar
build-by-default: true
branches:
- main
- dev
projects:
  BossBar:
    path: ""
    libs:
      - src: thebigsmileXD/apibossbar/apibossbar
        version: ^0.1.6
        branch: feature/color

...
