# VERSION: 1.3
# Coded By Theslowaja & RevXZ

# Task Delay (In Seconds)
task-delay: 5 #Seconds

# BossBar Color
# Available Color: pink, blue, red, green, yellow, purple, white
color: pink

# BossBar Main Configuration
bossBar:
  survival: #World Name
    title:
      - "Welcome To Survival"
      - "ServerMC"
    sub-title:
      - "play.servermc.net"
      - "www.servermc.net"
    percentage: 100
  default: #Default Configuration
    title:
      - "Welcome To Server"
      - "ServerMC"
    sub-title:
      - "play.servermc.net"
      - "www.servermc.net"
    percentage: 100

disabled-world:
  - "world_disabled_1"
  - "world_disabled_2"
