percentage: 100
color: "PINK" #PINK/BLUE/RED/GREEN/YELLOW/PURPLE/WHITE
# use & to get colors
BossBar:
  delay: 60
  Top-Title:
    - "Theslowaja BossBar"
    - "SimpleBossBar"
    - "Survival Server"
  Sub-Title:
    -

